### ISSUE TITLE
The logic that determines if a to-be-crawled website has the specific domain name needs to be fixed

### ISSUE THREAD

**Issue by yjhao** [buckyroberts/Spider#16]
In the current version, to determine if a to-be-crawled website has the specific domain name uses the code as follows:

`if Spider.domain_name not in url:`

However, this would not always be correct, considering the URL below:

https://twitter.com/intent/tweet?text=Videos&url=http%3A%2F%2Fmie.umass.edu%2Fvideos&original_referer=

The project domain name is mie.umass.edu. In this case, this URL certainly does not have "mie.umass.edu" as the domain name, but true is returned by using the `if Spider.domain_name not in url` logic.

This could be fixed by using the `get_domain_name` or `get_sub_domain_name` function to get the URL domain name, in contrast to a simple `in` logic.

**Comment by buckyroberts** [comment]
Thanks for pointing that out, I will work on it.

**Comment by astritzeqiri** [comment]
I fixed this by getting the comain name of the link:

if Spider.domain_name != get_domain_name(link):

**Comment by buckyroberts** [comment]
Fixed, thanks!
