### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character

### ISSUE THREAD

**Issue by shoaibkhan94** [buckyroberts/Spider#25]
Hey Bucky!
I tried a few things but couldn't get this sorted out. I am trying to crawl links from zomato. It works fine for most of the time but after some time it stops working throwing this error, as shown in the snapshot below. Could you help get this sorted out?

![image](https://cloud.githubusercontent.com/assets/8079189/15123005/4447ce54-163f-11e6-83e3-3e2fb5569105.png)

**Comment by buckyroberts** [comment]
Ok I will fix this in a bit. If you want to submit a pull request we can just use a try except statement for now. Something alone the lines of:

```
            try:
                f.write(item + "\n")
            except UnicodeEncodeError as e:
                print('UnicodeEncodeError: ' + item + str(e))
```
