### ISSUE TITLE
install pycharm and run, error "ImportError: No module named queue"

### ISSUE THREAD

**Issue by lohriialo** [buckyroberts/Spider#31]
`C:\Python27\python.exe C:/Users/user/Downloads/Spider-master/main.py
Traceback (most recent call last):
  File "C:/Users/user/Downloads/Spider-master/main.py", line 2, in <module>
    from queue import Queue
ImportError: No module named queue
Process finished with exit code 1`

Then I tried installing the module
Executed command: `pip install queue`

Error: `Could not find a version that satisfies the requirement queue (from versions: )
No matching distribution found for queue`

What did I do wrong or bucky, could you please update the documentation from a new user perspective setting up the whole thing?

**Comment by num3ri** [comment]
use "pithon3" and "pip3"

**Comment by lohriialo** [comment]
Thanks, got it working now after messing around for abit
