### ISSUE TITLE
convert between python 3.5 -> 2.7

### ISSUE THREAD

**Issue by tlt9116** [buckyroberts/Spider#35]
Hello,

When using python 2.7 and you try to  super().**init**(), which is perfectly find in python 3.5
TypeError: super() takes at least 1 argument (0 given). Can some tell my how to rewrite this so it would work in python 2.7

TIA,

TLT9116

**Comment by zhengjinzhj** [comment]
use this:
super(LinkFinder, self).__init__()

**Comment by yesanishhere** [comment]
Anyone looking into getting it to work on python 2.7.10 can use this: 
https://github.com/yesanishhere/python-crawler

**Comment by tlt9116** [comment]
Happy New Year Bucky,

Thank you for the link and continue doing your great videos!!

I have learned alot and think that I will continue!!

Thomas from Toulouse, France
